### ISSUE TITLE
Unable to compile on Windows. getting linking error

### ISSUE THREAD

**Issue by adityavemuri** [samiavasil/QtWebApp#1]
I have downloaded the files and build using qt creator.
I am getting below linkingg errors.
I can build the original QtWebApp from zip file.  I am able to build the websocket module seperately. but when I build the whole projects it  doesnt build

                                                                                                                                                     
ase/qwebsocket.o:qwebsocket.cpp:(.text+0x96): undefined reference to `_imp___ZTV10QWebSocket'                                                        
ase/qwebsocket.o:qwebsocket.cpp:(.text+0xe7): undefined reference to `_imp___ZTV10QWebSocket'                                                        
ase/qwebsocket.o:qwebsocket.cpp:(.text+0x117): undefined reference to `_imp___ZTV10QWebSocket'                                                       
ase/qwebsocket.o:qwebsocket.cpp:(.text+0x1a6): undefined reference to `_imp___ZTV10QWebSocket'                                                       
ase/qwebsocket.o:qwebsocket.cpp:(.text+0x7e5): undefined reference to `_imp___ZN27QWebSocketCorsAuthenticatorC1ERK7QString'                          
ase/qwebsocket.o:qwebsocket.cpp:(.text+0x858): undefined reference to `_imp___ZNK27QWebSocketCorsAuthenticator7allowedEv'                            
ase/qwebsocket.o:qwebsocket.cpp:(.text+0x941): undefined reference to `_imp___ZN27QWebSocketCorsAuthenticatorD1Ev'                                   
ase/qwebsocket.o:qwebsocket.cpp:(.text+0x963): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                     
ase/qwebsocket.o:qwebsocket.cpp:(.text+0xdc8): undefined reference to `_imp___ZN27QWebSocketCorsAuthenticatorD1Ev'                                   
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0xa9): undefined reference to `_imp___ZN10QWebSocket4pongEyRK10QByteArray'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x5b8): undefined reference to `_imp___ZN10QWebSocket5errorEN15QAbstractSocket11SocketErrorE'             
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x668): undefined reference to `_imp___ZN10QWebSocket27proxyAuthenticationRequiredERK13QNetworkProxyP14QAu
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x70c): undefined reference to `_imp___ZN10QWebSocket19readChannelFinishedEv'                             
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x7b0): undefined reference to `_imp___ZN10QWebSocket12aboutToCloseEv'                                    
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x856): undefined reference to `_imp___ZN10QWebSocket12bytesWrittenEx'                                    
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0xac6): undefined reference to `_imp___ZN10QWebSocket34preSharedKeyAuthenticationRequiredEP29QSslPreShared
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0xb6c): undefined reference to `_imp___ZN10QWebSocket12bytesWrittenEx'                                    
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0xc0e): undefined reference to `_imp___ZN10QWebSocket9sslErrorsERK5QListI9QSslErrorE'                     
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0xd67): undefined reference to `_imp___ZN10QWebSocket17textFrameReceivedERK7QStringb'                     
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0xde4): undefined reference to `_imp___ZN10QWebSocket19binaryFrameReceivedERK10QByteArrayb'               
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0xe89): undefined reference to `_imp___ZN10QWebSocket21binaryMessageReceivedERK10QByteArray'              
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0xf2e): undefined reference to `_imp___ZN10QWebSocket19textMessageReceivedERK7QString'                    
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x129b): undefined reference to `_imp___ZN10QWebSocket12bytesWrittenEx'                                   
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x1926): undefined reference to `_imp___ZN10QWebSocket12stateChangedEN15QAbstractSocket11SocketStateE'    
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x1ae3): undefined reference to `_imp___ZN10QWebSocket5errorEN15QAbstractSocket11SocketErrorE'            
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x1c80): undefined reference to `_imp___ZN10QWebSocket12aboutToCloseEv'                                   
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x1dc1): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x24c0): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x254d): undefined reference to `_imp___ZN10QWebSocket5errorEN15QAbstractSocket11SocketErrorE'            
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x2601): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x26dd): undefined reference to `_imp___ZN10QWebSocket5errorEN15QAbstractSocket11SocketErrorE'            
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x2878): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x28cb): undefined reference to `_imp___ZN10QWebSocket5errorEN15QAbstractSocket11SocketErrorE'            
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x2a4c): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x2a99): undefined reference to `_imp___ZN10QWebSocket5errorEN15QAbstractSocket11SocketErrorE'            
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x2c90): undefined reference to `_imp___ZN10QWebSocket12stateChangedEN15QAbstractSocket11SocketStateE'    
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x2eba): undefined reference to `_imp___ZN10QWebSocket12stateChangedEN15QAbstractSocket11SocketStateE'    
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x2ff3): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x3079): undefined reference to `_imp___ZN10QWebSocket5errorEN15QAbstractSocket11SocketErrorE'            
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x30a6): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x30f0): undefined reference to `_imp___ZN10QWebSocket5errorEN15QAbstractSocket11SocketErrorE'            
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x3762): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x3811): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x3e97): undefined reference to `_imp___ZN10QWebSocketC1EP10QTcpSocketN18QWebSocketProtocol7VersionEP7QObj
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x3ff4): undefined reference to `_imp___ZN10QWebSocket19setSslConfigurationERK17QSslConfiguration'        
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x48d7): undefined reference to `_imp___ZN10QWebSocket12disconnectedEv'                                   
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x4957): undefined reference to `_imp___ZN10QWebSocket12stateChangedEN15QAbstractSocket11SocketStateE'    
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x4bf7): undefined reference to `_imp___ZN10QWebSocket5errorEN15QAbstractSocket11SocketErrorE'            
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x4efd): undefined reference to `_imp___ZN10QWebSocket12stateChangedEN15QAbstractSocket11SocketStateE'    
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x5458): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x553a): undefined reference to `_imp___ZN10QWebSocket5errorEN15QAbstractSocket11SocketErrorE'            
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x595b): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x59d2): undefined reference to `_imp___ZN10QWebSocket12stateChangedEN15QAbstractSocket11SocketStateE'    
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x59e4): undefined reference to `_imp___ZN10QWebSocket9connectedEv'                                       
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x6215): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x64b7): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x65ff): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x66e1): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x678a): undefined reference to `_imp___ZN10QWebSocket16staticMetaObjectE'                                
ase/qwebsocket_p.o:qwebsocket_p.cpp:(.text+0x68e0): more undefined references to `_imp___ZN10QWebSocket16staticMetaObjectE' follow                   
ase/qwebsocketserver.o:qwebsocketserver.cpp:(.text+0x4c): undefined reference to `_imp___ZTV16QWebSocketServer'                                      
ase/qwebsocketserver.o:qwebsocketserver.cpp:(.text+0x97): undefined reference to `_imp___ZTV16QWebSocketServer'                                      
ase/qwebsocketserver.o:qwebsocketserver.cpp:(.text+0xc7): undefined reference to `_imp___ZTV16QWebSocketServer'                                      
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x35d): undefined reference to `_imp___ZN16QWebSocketServer15peerVerifyErrorERK9QSslError'    
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x3f5): undefined reference to `_imp___ZN16QWebSocketServer9sslErrorsERK5QListI9QSslErrorE'   
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x48d): undefined reference to `_imp___ZN16QWebSocketServer34preSharedKeyAuthenticationRequire
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x550): undefined reference to `_imp___ZN16QWebSocketServer11acceptErrorEN15QAbstractSocket11S
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x9d2): undefined reference to `_imp___ZN16QWebSocketServer11serverErrorEN18QWebSocketProtocol
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0xc6f): undefined reference to `_imp___ZN16QWebSocketServer16staticMetaObjectE'               
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0xcaf): undefined reference to `_imp___ZN10QWebSocket5closeEN18QWebSocketProtocol9CloseCodeERK
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0xff7): undefined reference to `_imp___ZN16QWebSocketServer16staticMetaObjectE'               
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x109a): undefined reference to `_imp___ZN27QWebSocketCorsAuthenticatorC1ERK7QString'         
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x10ce): undefined reference to `_imp___ZN16QWebSocketServer28originAuthenticationRequiredEP27
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x1111): undefined reference to `_imp___ZNK27QWebSocketCorsAuthenticator7allowedEv'           
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x1223): undefined reference to `_imp___ZN16QWebSocketServer13newConnectionEv'                
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x124a): undefined reference to `_imp___ZN27QWebSocketCorsAuthenticatorD1Ev'                  
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x1254): undefined reference to `_imp___ZN16QWebSocketServer16staticMetaObjectE'              
ase/qwebsocketserver_p.o:qwebsocketserver_p.cpp:(.text+0x12c9): undefined reference to `_imp___ZN27QWebSocketCorsAuthenticatorD1Ev'

**Comment by samiavasil** [comment]
Can you give more information what exactly you do. Please try to open  Demo1.pro in qtcreator and build it - it should be compiled and linked successfully.     If not please give me information about versions of QT and qtcreator which you use in order to reproduce the problem in my side.

**Comment by samiavasil** [comment]
Do you still have a linkage problem??

**Comment by samiavasil** [comment]
If yes please reopen and explain more...
